### ISSUE TITLE
Web app - The lesser number - IBM's callforcode'19

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#1]
Everything on earth should live as accessible and valid data setting a base. The private and protected data can live on a permissioned ledger. The public data can be available as a web app. This would be evolution having the data visualisations. This project is based on social and environment issues. In this project the intern w/ me would collect data and create statistics on the listed things in a web app. This project would be a IBM's callforcode'19 submission.

- Beggars
- BPLs
- Child deaths
- Child labour
- Child marriage
- Child widows
- Domestically abused people
- Gender
- Heinous criminal case
- Illiterates
- Fatal illness 
- People w/ disabilities
- People lacking in basic living needs like food, water and electricity. 
- Race
- Refugees
- Religion
- Sex workers
- Sexual orientation
- Warzones

The work - 

- Data collection - interns
- Website creation - intern
- Statistics + Time series charts - @tapaswenipathak + intern
- Visualisation - intern + @tapaswenipathak review
- Design - @tapaswenipathak.

A lot of information can pulled from [data.worldbank.org](https://data.worldbank.org/) , every country mostly have their data.org. Anything unavailable would be collected from field interns.

**Comment by sakshivij** [comment]
@tapaswenipathak I need to collect data for the topics mentioned above and write the origin from where I find the data in a separate file?

**Comment by tapaswenipathak** [comment]
On Sun, May 19, 2019 at 10:38 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> @tapaswenipathak I should collect data for the topics mentioned above and write the origin from where I find the data in a separate file?

You should do the tasks assigned. We can have a call if you need any
help https://calendly.com/tapaswenipathak.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by jsxs0** [comment]
Hey, I'm interested in working for this. Is there anybody already working on it, or can we've a conversation?
Truth to be told, I'm pretty interested in IBM's callforcode'19 but I could not really find a team, and/or a proper task to work on, so, if the intern (who'd be working over this) would be a part of this callforcode'19 team, I'm in it. Can I start curating APIs, websites from web? Referencing #32 here
TIA.

**Comment by nightwarriorftw** [comment]
```Updates``` 
https://drive.google.com/file/d/1n_5s36aBU8qEZzYmIrNA8g2_rHX1CqF5/view?usp=sharing

**Comment by tapaswenipathak** [comment]
On Sat, Jul 20, 2019 at 12:24 AM nightwarrior-xxx
<notifications@github.com> wrote:
>
> Updates
> https://drive.google.com/file/d/1n_5s36aBU8qEZzYmIrNA8g2_rHX1CqF5/view?usp=sharing

Nice! can you add the branch w/ the work; review from @sujaykumarreddy.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
