### ISSUE TITLE
How the outliers in notebook visualisation implementations should be

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#102]
As I told guys, I am adding a sample notebook implementation, copy it.

**Comment by bymayanksingh** [comment]
can you link it here?

**Comment by ucalyptus** [comment]
pls link it here

**Comment by tapaswenipathak** [comment]
Kicked off - https://drive.google.com/drive/folders/1K81aYxlpms2UoewBfKfDv_A92AYESy53
