### ISSUE TITLE
Reminder: More Data Collection

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#103]
Folks, the current information lack on data, seeing the notebooks, say that last 70 years of data collected; use arms, collect from

- API 
- Scraping
- Tables
- Websites
- Publications
- Anything else

Let me know people who can help me w/ this. No degradation but data collection is actually cheap task, I have more implementation ideas on how we can showcase the information, let me know people interested on exploring these topics.

**Comment by Aashi15bansal** [comment]
I can collect the data using web-scraping

**Comment by ucalyptus** [comment]
ack

**Comment by tapaswenipathak** [comment]
On Fri, Jul 19, 2019 at 8:30 AM Aashi15bansal <notifications@github.com> wrote:
>
> I can collect the data using web-scraping

Nice, can you cut a paper doc on what all websites you wanna scrape? I
can pitch in for generalised scraper.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by Aashi15bansal** [comment]
@tapaswenipathak  can i get till next sunday's time to do this ? Because by this sunday I need to finish linux ticket

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/Generalised-Scraper--AhaUuzJsPk6McECHDFIW4oMUAQ-A1SxhqXvXnqWiFGvksw6U
