### ISSUE TITLE
Asking about what to do?

### ISSUE THREAD

**Issue by prateekmaj21** [tapaswenipathak/TheLesserNumber#104]
https://www.infoplease.com/ethnicity-and-race-countries

@tapaswenipathak mam do i plot the data for each nation separately , i am asking about this link as it was given in the repository

**Comment by tapaswenipathak** [comment]
On Fri, Jul 19, 2019 at 7:39 AM Prateek Majumder
<notifications@github.com> wrote:
>
> https://www.infoplease.com/ethnicity-and-race-countries
>
> @tapaswenipathak mam do i plot the data for each nation separately , i am asking about this link as it was given in the repository

Sure, we can chat, can you schedule using
https://calendar.google.com/calendar/r or we can chat after 9:00 in
Slack.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
