### ISSUE TITLE
API, Websites, Articles, Publishes

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#31]
@prondubuisi I will be writing useful information in this ticket, I would suggest opening wikipedia article and exploring the sections, I think you can find all the information as shown 

from https://github.com/tapaswenipathak/TheLesserNumber/issues/31.

## Timeline

https://github.com/tapaswenipathak/Timelines/pull/4#issue-280246105

### Child Labour
<img width="1100" alt="Screen Shot 2019-05-22 at 6 18 54 PM" src="https://user-images.githubusercontent.com/4143778/58175589-16d1f600-7cbe-11e9-92de-489b131adc17.png">

### LGBT Rights
- 
<img width="1092" alt="Screen Shot 2019-05-22 at 6 17 21 PM" src="https://user-images.githubusercontent.com/4143778/58175500-e0947680-7cbd-11e9-82d5-be4564f0c59a.png">

### Domestic abuse
- http://evaw-global-database.unwomen.org/en/countries/africa/nigeria

### Religion
<img width="1076" alt="Screen Shot 2019-05-22 at 6 13 03 PM" src="https://user-images.githubusercontent.com/4143778/58175217-42a0ac00-7cbd-11e9-8038-3449038f8694.png">

### Races
- https://www.infoplease.com/world/countries/nigeria

### Disability
- https://www.premiumtimesng.com/news/more-news/288954-19-million-nigerians-living-with-disability-official.html
- 
<img width="1015" alt="Screen Shot 2019-05-22 at 6 04 45 PM" src="https://user-images.githubusercontent.com/4143778/58174690-17698d00-7cbc-11e9-859b-f205f4c592c2.png">

### Warzones
- 
<img width="1069" alt="Screen Shot 2019-05-22 at 6 03 13 PM" src="https://user-images.githubusercontent.com/4143778/58174605-e721ee80-7cbb-11e9-8223-0dac0112bfea.png">

### Criminal case
- https://www.bjs.gov/content/pub/pdf/wfbcjsnig.pdf

### Refugees

- https://www.unhcr.org/nigeria-emergency.html
- <img width="1025" alt="Screen Shot 2019-05-22 at 6 00 51 PM" src="https://user-images.githubusercontent.com/4143778/58174417-8e525600-7cbb-11e9-9691-d7a9b212c1f3.png">

### Child Deaths

- https://www.ncbi.nlm.nih.gov/pubmed/12318627
- https://data.unicef.org/topic/child-survival/under-five-mortality/
- https://data.worldbank.org/indicator/sh.dyn.mort

### BPL

- http://data.worldbank.org/indicator/SI.POV.GINI/
- http://unpan1.un.org/intradoc/groups/public/documents/IDEP/UNPAN003895.pdfhttps://web.archive.org/web/20150424153316/http://www.nigerianstat.gov.ng/pages/download/41
- https://tradingeconomics.com/nigeria/poverty-headcount-ratio-at-national-poverty-line-percent-of-population-wb-data.html
- http://povertydata.worldbank.org/poverty/country/NGA
- <img width="1147" alt="Screen Shot 2019-05-22 at 5 46 37 PM" src="https://user-images.githubusercontent.com/4143778/58173665-927d7400-7cb9-11e9-96a9-a235d458a3d1.png">

### Child Widows

- http://actiononchildearlyandforcedmarriage.org/wp-content/uploads/2018/08/ChildWidowsReport_2018_Mohinder_Watson.pdf
- http://www.theloombafoundation.org/images/The%20Global%20Widows%20Report%202015.pdf
- https://www.un.org/womenwatch/daw/public/wom_Dec%2001%20single%20pg.pdf
- https://dergipark.org.tr/download/article-file/540392
- 
<img width="1161" alt="Screen Shot 2019-05-22 at 5 55 30 PM" src="https://user-images.githubusercontent.com/4143778/58174171-df157f00-7cba-11e9-9df4-1013ae3716ab.png">

## Fatal illness

- https://www.who.int/csr/don/archive/year/en/

**Comment by prondubuisi** [comment]
Lol, thanks for this
