### ISSUE TITLE
Create Jupyter Notebook per data sample

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#70]

**Comment by nightwarrior-xxx** [comment]
There should be a checklist to track for which dataset Jupyter notebook has been created and has to be created.
@tapaswenipathak  PTAL

**Comment by nightwarrior-xxx** [comment]
## Checklist of Notebooks

- [x] Child Death [@anantmoudgalya ]
- [x] Fatal Illnesses [@anantmoudgalya ]
- [ ] Others

**Comment by nightwarrior-xxx** [comment]
The Checklist
- [x]
- [x] 
- [x]
- [x]
- [x]
- [x]

**Comment by nightwarriorftw** [comment]
## The checklist 

-  Fatal Illnesses    (@anantmoudgalya)
    - [x] Fatal Illnesses 
-  Child Death        (@anantmoudgalya)
    - [x] Child Death
- Child Labour Data (@nightwarrior-xxx)
    - [x] Census-2001&2011
    - [x] Census1971to2001
    - [ ] Child-labour-database_Nov-2017
- crime data (@shah-aman)
     - [ ] Crime data
- Heinous Criminal Data (@shah-aman) 
    - [ ] rape at national level
    - [ ] international homicided data
    - [ ] murder rates

**Comment by tapaswenipathak** [comment]
Sample and level - https://github.com/ebov/space-time/tree/master/Scripts/notebooks.

**Comment by ucalyptus** [comment]
Ack and doing

**Comment by shah-aman** [comment]
ack and on  it

**Comment by shah-aman** [comment]
- [ ] crime data(@shah-aman )

- [ ] time series(@shah-aman )

**Comment by shah-aman** [comment]
crime data we have is of only Maryland state.
