### ISSUE TITLE
Create appealing and informative visualisations from numerical data files

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/TheLesserNumber#80]
- seaborn
- matplotlib
- tableau

**Comment by kumar-hardik** [comment]
on which datasets? the ones i uploaded?

**Comment by tapaswenipathak** [comment]
On Mon, Jun 24, 2019 at 8:37 PM Hardik Kumar <notifications@github.com> wrote:
>
> on what datasets? the ones i uploaded?

I am available on Slack. Let's talk there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
